service: tipsy-tourist-lambda
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  stage: prod
  region: eu-west-2
  environment:
    GOOGLE_MAPS_API_KEY: ${env:GOOGLE_MAPS_API_KEY}
  httpApi:
    cors: true

functions:
  function:
    handler: index.handler
    events:
      - httpApi:
          path: /test
          method: get
  places:
    handler: routes/placesRoute.places
    events:
      - httpApi:
          path: /places
          method: post
  attractions:
    handler: routes/attractionsRoute.attractions
    events:
      - httpApi:
          path: /attractions
          method: post
  getDetails:
    handler: routes/getDetailsRoute.getDetails
    events:
      - httpApi:
          path: /get-details
          method: post
  geocode:
    handler: routes/geocodeRoute.geocode
    events:
      - httpApi:
          path: /geocode
          method: post
